# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Chelsea/Documents/GitHub/ECE540FinalProject/Vivado/runnable_projectMBlatestBitstream/finalMBversion.srcs/sources_1/ip/worldmap_level1/worldmap_level1.xci
# IP: The module: 'worldmap_level1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Chelsea/Documents/GitHub/ECE540FinalProject/Vivado/runnable_projectMBlatestBitstream/finalMBversion.srcs/sources_1/ip/worldmap_level1/worldmap_level1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'worldmap_level1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Chelsea/Documents/GitHub/ECE540FinalProject/Vivado/runnable_projectMBlatestBitstream/finalMBversion.srcs/sources_1/ip/worldmap_level1/worldmap_level1.xci
# IP: The module: 'worldmap_level1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Chelsea/Documents/GitHub/ECE540FinalProject/Vivado/runnable_projectMBlatestBitstream/finalMBversion.srcs/sources_1/ip/worldmap_level1/worldmap_level1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'worldmap_level1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
